sudo: required
services: 
  - docker
before_install: 
  - docker build -t rishabh.911996/react-test -f ./client/Dockerfile.dev ././client

script: 
  - docker run -e CI=true rishabh.911996/react-test npm test -- --coverage

after_success: 
  -docker build -t rishabh.911996/multi-client ./client
  -docker build -t rishabh.911996/multi-nginx ./nginx
  -docker build -t rishabh.911996/multi-server ./server
  -docker build -t rishabh.911996/multi-worker ./worker