sudo: required
sevices:
  - docker
before_install:
  - docker build -t rishabh.911996/docker-react -f Dockerfile.dev .

script:
  - docker run rishabh.911996/docker-react npm run test

deploy:
  provider: elsaticbeanstalk
  region: us-east-1
  app: docker-react
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-141102535296"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: 
  secure: "$AWS_SECRET_KEY"