sudo: requried
sevices:
  - docker
before_install:
  - docker build -t rishabh.911996/docker-react -f Dockerfile.dev .
script:
  - docker run rishabh.911996/docker-react npm run test -- --coverage